apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: new-decleare
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/sohag033/app1.git'
    targetRevision: HEAD
    path: ./just
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
