apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: ngnix-decleare
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/sohag033/app1.git'
    targetRevision: HEAD
    path: .
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
