apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: app/
    repoURL: https://github.com/sohag033/app1.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true